# pandoc-crossref
chapters: True
linkReferences: True
nameInLink: True
figureTitle: |
  <span class="captionprefix">Figure
tableTitle: |
  <span class="captionprefix">Table
titleDelim: ".</span><br>"
figPrefix:
  - "figure"
  - "figures"
subfigureTemplate: $$figureTitle$$ $$i$$$$titleDelim$$ $$t$$
subfigureChildTemplate: <span class="captionprefix">($$i$$)</span> $$t$$
tblPrefix:
  - "tableau"
  - "tableaux"
eqnPrefix:
  - "équation"
  - "équations"
eqnPrefixTemplate: $$p$$&nbsp;$$i$$
secPrefix:
  - "section"
  - "sections"
tableEqns: True
sectionsDepth: 3
# numberSections: true

references-section-title: True
link-citations: True
bibliography: "_assets/refs/refs.json"
notes-after-punctuation: True